profile_workshop_dbt:
  outputs:
    dev:
      type: duckdb
      path: C:\GIT\dbt\workshop_dbt\dev.db
      threads: 1

    prod:
      type: duckdb
      path: C:\GIT\dbt\workshop_dbt\pro.db
      threads: 4

  target: dev

proj_workshop:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
